sudo: required
language: generic

services: 
    - docker

before_install: 
    - docker build -t victorbarolle/docker-react -f Dockerfile.dev .

script: 
    - docker run -e CI=true victorbarolle/docker-react npm run test